import { getApiBase, getAuthHeadersForApi } from './server-streaming';

/**
 * Ask the server for three alternative titles for a conversation, generated by
 * the model that wrote its last reply. Throws with the server's explanation
 * (e.g. a private conversation on a cloud model) when it can't.
 */
export async function suggestTitles(conversationId: string, signal?: AbortSignal): Promise<string[]> {
  const response = await fetch(
    `${getApiBase()}/api/conversations/${encodeURIComponent(conversationId)}/title-suggestions`,
    { method: 'POST', headers: getAuthHeadersForApi(), signal },
  );
  const body = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(body.error || `Couldn't suggest titles (HTTP ${response.status})`);
  }
  return Array.isArray(body.titles) ? body.titles : [];
}
